### ISSUE TITLE
Check for node-semver test suite

### ISSUE THREAD

**Issue by opilar** [steveklabnik/semver-parser#36] opened 2017-11-28 11:03 UTC
Port and launch [node-semver tests](https://github.com/npm/node-semver/tree/master/test).

Look for discussion in #32.

**Comment by udoprog** [comment] 2017-12-08 21:05
These should probably be implemented in https://github.com/steveklabnik/semver since the necessary methods to exercise the tests live there (comparisons, matches, ...).

**Comment by opilar** [comment] 2017-12-08 22:26
Currently I'm in the middle of porting. Node semver has more functions and I just skip this tests.

**Comment by udoprog** [comment] 2017-12-08 22:29
@opilar How far along are you? I'd like to add https://raw.githubusercontent.com/npm/node-semver/master/test/index.js in https://github.com/steveklabnik/semver since it relies heavily on how comparisons are implemented. Can I go ahead with that?

**Comment by udoprog** [comment] 2017-12-08 23:22
This is what I've done so far. I mostly just threw it together to personally make sure that #34 didn't introduce any regressions:
https://github.com/udoprog/semver/commit/5d1a6f945b3e9596b7bb6abc501015d90b1f9457

The new (and recently merged) parser actually passes these, while the old one fails with:
```
the given version requirement is invalid: >=*
```

**Comment by judu** [comment] 2018-02-20 13:29
There is a difference between the node parser and this one: the comma to imply the "and". Is this intended?

I'm interested because I would like to have a "semver" cli like the node one, but not running on node. The "comma" VS "spaces" choice forces me to "fix" the range string before having it parsed.

So if I could have that behaviour changed in here, that would save me trouble :D

**Comment by steveklabnik** [comment] 2021-05-25 21:08
This crate is no longer being used or maintained: https://github.com/steveklabnik/semver-parser/commit/dc6c1077899da46e89242041dda54ca36c170982

**Closed as completed by steveklabnik** 2021-05-25 21:08 UTC
