### ISSUE TITLE
build error on `#![rustfmt::skip]`

### ISSUE THREAD

**Issue by dwarburt** [steveklabnik/semver-parser#52] opened 2020-10-27 20:02 UTC
Today I had a build error while trying to build the brave browser

       Compiling semver-parser v0.10.1
    error[E0658]: non-builtin inner attributes are unstable
     --> /home/david/git/fork/brave-browser/src/brave/build/rustup/0.1.4/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
      |
    4 | #![rustfmt::skip]
      | ^^^^^^^^^^^^^^^^^
      |
      = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information
    
       Compiling tracing-log v0.1.1
    error: aborting due to previous error
    
    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `semver-parser`.
    
    
It seems like that comes from this line: https://github.com/steveklabnik/semver-parser/blob/4ad3c7b10496d0007af2f327cb50a9897b5b969f/tests/genpest.rs#L17 but in order to get it to build I had to delete this line https://github.com/steveklabnik/semver-parser/blob/4ad3c7b10496d0007af2f327cb50a9897b5b969f/src/generated.rs#L4  from my local working copy, and after that it builds fine.

**Comment by steveklabnik** [comment] 2020-10-28 15:13
https://github.com/steveklabnik/semver/issues/218 is the same issue in another crate.

This is *very* strange...

**Comment by kentfredric** [comment] 2020-10-30 08:36
My analysis indicates that that syntax only started being legal in rust 1.44.

I can build semver-parser 0.10.1 on all rusts newer than 1.44, but all older ones fail.

So to me it looks like, the only regression here is the one added in 0.10.1 with 9e01cd3a0990ba3057d5a5cd9f70eeb01209fb93 

https://kentfredric.github.io/rust-vmatrix/#crate-s
![snapshot_20201030_213431](https://user-images.githubusercontent.com/44790/97677839-c4724700-1af7-11eb-9500-a8765efd73eb.png)
https://kentfredric.github.io/rust-vmatrix/semver-parser/
![snapshot_20201030_213554](https://user-images.githubusercontent.com/44790/97677944-ec61aa80-1af7-11eb-9538-2ad77c0c820b.png)

**Comment by steveklabnik** [comment] 2020-11-02 17:03
Whelp, I did not know this, and thought it was used previously. Sorry about the noise.

**Comment by djc** [comment] 2020-11-03 09:07
Not sure why this was closed? #54 fixes it and sets up MSRV testing in CI.

**Comment by steveklabnik** [comment] 2020-11-05 17:51
I thought this was the ticket in rust-lang/rust 😅😓

**Comment by j-maas** [comment] 2020-12-18 19:19
For those running into this error message: Check that you are not running an older version of Rust by executing `rustup update`.

**Comment by steveklabnik** [comment] 2021-01-05 22:14
This should be fixed in 0.10.2.

**Closed as completed by steveklabnik** 2021-01-05 22:14 UTC
