### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by adrian-rt** [steveklabnik/semver-parser#56] opened 2020-11-27 17:25 UTC
Hi,

I'm trying to install grcov whch has a dependency on this package and I get this error:

  build failed
adrian@adrian-XPS-15-9570:~/.cargo$ cargo install  semver-parser
    Updating crates.io index
  Installing semver-parser v0.10.1
   Compiling ucd-trie v0.1.3
   Compiling pest v2.1.3
   Compiling semver-parser v0.10.1
error[E0658]: non-builtin inner attributes are unstable
 --> /home/adrian/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
  |
4 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `semver-parser v0.10.1`, intermediate artifacts can be found at `/tmp/cargo-installrVTaRR`

Caused by:
  could not compile `semver-parser`.

To learn more, run the command again with --verbose.

Thank you!

**Comment by j-maas** [comment] 2020-12-18 19:15
Seems like a duplicate of #52.

**Comment by steveklabnik** [comment] 2021-01-05 22:16
Hi, semver-parser doesn't have a real binary, so trying to install it with `cargo install` doesn't make sense.

Beyond that, this specific compiler error should be fixed now, but you should depend on it like any other cargo package, not install with cargo install. Thanks / sorry.

**Closed as completed by steveklabnik** 2021-01-05 22:16 UTC
