### ISSUE TITLE
Support parsing range sets

### ISSUE THREAD

**Issue by KodrAus** [steveklabnik/semver-parser#22] opened 2017-10-21 01:03 UTC
The npm `semver` package [supports parsing sets of versions](https://docs.npmjs.com/misc/semver#ranges) separated by some operator.

It would be great if `semver_parser` also supported `VersionReq` (what npm calls `Comparator`) ranges where the versions are separated by:

- `||` for logical `or` ranges
- whitespace for logical `and` ranges

Are there any others in the `npm` package we should also support?

I think this will need more discussion if we want to produce mentoring instructions someone can use to implement it. At least we should nail down exactly what we want to support on top of what `semver_parser` already does.

# Mentoring instructions

Leave a comment here on the thread and we'll work out how to get started.

**Comment by udoprog** [comment] 2017-11-26 13:50
Hey,

I'm playing around with rewriting the parser for semver as a simple lexer + recursive-descent parser here:
https://github.com/udoprog/semver-parser/tree/recursive-descent

The rationale is:
* Make error reporting more predictable.
* Can be convinced to report the spans where the error ocurred.
* More cleanly support these kinds of features without resorting to splitting splits, since the parser ends up being more composable.

The way I'm doing it would (probably) also permit swapping out the parser for an LR(1) parser generated by [lalrpop](https://github.com/nikomatsakis/lalrpop).

_Please note_ that this is only an experiment that I've spent a couple of hours playing around with. I'm at the stage where I'd like to get feedback if this is something desirable for this project or not.

**Comment by steveklabnik** [comment] 2017-11-26 15:43
Neat!

What mostly matters to this project is:

1. correctness
2. no dependencies
3. ease of maintenance
4. errors
5. performance

I'm not really particularly tied to internals other than those things.

**Comment by udoprog** [comment] 2017-11-26 18:24
Thanks.

The implementation is now feature complete according to the tests available.

A minor benchmark seems to indicate that it has a slight edge over the current approach, probably because most decisions can be made using a single pass and only one token of lookahead. More importantly there's probably no significant regression (all though this hasn't been rigorously tested):
```
test range::tests::bench_simple_version        ... bench:         236 ns/iter (+/- 46)
test range_parser::tests::bench_simple_version ... bench:         198 ns/iter (+/- 19)
```

There are two improvements I'd like to accomplish with the current parser at some point:

* I've noticed that there is no test coverage for how to deal with whitespace in the middle of version requirements. So the rec-desc parser currently accepts `> 0.    1`, while the old one doesn't. See: https://github.com/udoprog/semver-parser/commit/b76af35c863d73c17ae10dd5c723f394b0588cb6
 I've opened #32 for this.
* Pre-release identifiers currently require copying for no good reason. I've prepared the infrastructure in the parser I built to do this, but it could also be ported back.
 I've opened #33 for this.

**Comment by steveklabnik** [comment] 2018-06-18 17:39
I merged this in, so I think this is good now?

**Closed as completed by steveklabnik** 2018-06-18 17:39 UTC
Labels: enhancement

**Comment by kira-bruneau** [comment] 2019-11-20 05:05
@steveklabnik I think this issue should be reopened. Walking the [nodejs dependencies of nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/node-packages/node-packages-v10.json) with semver I can't parse the following VerisonReqs:

**Unions:**
- [@cycle/run: 5.4.0](https://registry.npmjs.org/@cycle/run)
  - xstream: "10.x || 11.x"
- [eslint_d: 8.0.0](https://registry.npmjs.org/eslint_d/8.0.0)
  - eslint: "^4 || ^5 || ^6"
- [fs-write-stream-atomic: 1.0.10](https://registry.npmjs.org/fs-write-stream-atomic/1.0.10)
  - readable-stream: "1 || 2"
- [init-package-json: 1.10.3](https://registry.npmjs.org/init-package-json/1.10.3)
  - npm-package-arg: "^4.0.0 || ^5.0.0 || ^6.0.0"
  - read-package-json: "1 || 2"
  - semver: "2.x || 3.x || 4 || 5"  
- [gulp-less: 3.5.0](https://registry.npmjs.org/gulp-less/3.5.0)
  - less: "2.6.x || ^2.7.1"
- [glob: 6.0.4](https://registry.npmjs.org/glob/6.0.4)
  - minimatch: "2 || 3"
- [loose-envify: 1.4.0](https://registry.npmjs.org/loose-envify/1.4.0)
  - js-tokens: "^3.0.0 || ^4.0.0"  
- [node-gyp: 3.6.3](https://registry.npmjs.org/node-gyp/3.6.3)
  - nopt: "2 || 3"
  - npmlog: "0 || 1 || 2 || 3 || 4"
- [npm-profile: 4.0.2](https://registry.npmjs.org/npm-profile/4.0.2)
  - aproba: "^1.1.2 || 2"
- [npm-registry-client: 8.6.0](https://registry.npmjs.org/npm-registry-client/8.6.0)
  - normalize-package-data: "~1.0.1 || ^2.0.0"
  - npm-package-arg: "^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0"
  - semver: "2 >=2.2.1 || 3.x || 4 || 5"
  - npmlog: "2 || ^3.1.0 || ^4.0.0"
- [wide-align: 1.1.3](https://registry.npmjs.org/wide-align/1.1.3)
  - string-width: "^1.0.2 || 2"
- [yargs: 12.0.5](https://registry.npmjs.org/yargs/12.0.5)
  - y18n: "^3.2.1 || ^4.0.0"

**Space Delimited Intersections:**
- [@antora/ui-loader: 2.2.0](https://registry.npmjs.org/@antora/ui-loader)
  - gulp-vinyl-zip: "~2.1 >=2.1.2"
- [@slack/client: 3.16.0](https://registry.npmjs.org/@slack/client)
  - request: ">=2.0.0 <2.77.0"
- [bower2nix/3.2.0](https://registry.npmjs.org/bower2nix/3.2.0)
  - bower: ">=1.2.8 <2"
  - semver: ">=5.1.0 <6"  
- [callback-stream/1.1.0](https://registry.npmjs.org/callback-stream/1.1.0)
  - readable-stream: "> 1.0.0 < 3.0.0"
- [compressible/2.0.17](https://registry.npmjs.org/compressible/2.0.17)
  - mime-db: ">= 1.40.0 < 2"
- [connect/2.14.5](https://registry.npmjs.org/connect/2.14.5)
  - debug: ">= 0.7.3 < 1"
- [fstream/1.0.12](https://registry.npmjs.org/fstream/1.0.12)
  - mkdirp: ">=0.5 0"
- [github-slugger/1.2.1](https://registry.npmjs.org/github-slugger/1.2.1)
  - emoji-regex: ">=6.0.0 <=6.1.1"
- [hasher/1.2.0](https://registry.npmjs.org/hasher/1.2.0)
  - signals: ">0.7 <2.0"
- [http-errors/1.7.3  ](https://registry.npmjs.org/http-errors/1.7.3  )
  - statuses: ">= 1.5.0 < 2"
- [iconv-lite/0.5.0](https://registry.npmjs.org/iconv-lite/0.5.0)
  - safer-buffer: ">= 2.1.2 < 3"
- [jsdom/7.2.2](https://registry.npmjs.org/jsdom/7.2.2)
  - cssom: ">= 0.3.0 < 0.4.0"
  - cssstyle: ">= 0.2.29 < 0.3.0"
  - nwmatcher: ">= 1.3.7 < 2.0.0"
  - symbol-tree: ">= 3.1.0 < 4.0.0"
  - xml-name-validator: ">= 2.0.1 < 3.0.0"
- [JSONStream/1.3.5](https://registry.npmjs.org/JSONStream/1.3.5)
  - through: ">=2.2.7 <3"
- [mooremachine/2.3.0](https://registry.npmjs.org/mooremachine/2.3.0)
  - assert-plus: ">=0.2.0 <0.3.0"
- [node-gyp/3.6.3](https://registry.npmjs.org/node-gyp/3.6.3)
  - request: ">=2.9.0 <2.82.0"
- [optimist/0.2.8](https://registry.npmjs.org/optimist/0.2.8)
  - wordwrap: ">=0.0.1 <0.1.0"
- [protobufjs/3.8.2](https://registry.npmjs.org/protobufjs/3.8.2)
  - bytebuffer: "~3 >=3.5"
- [rethinkdb/2.3.3](https://registry.npmjs.org/rethinkdb/2.3.3)
  - bluebird: ">= 2.3.2 < 3"
- [s3http/0.0.5](https://registry.npmjs.org/s3http/0.0.5)
  - aws-sdk: ">=1.2.0 <2"
- [sshpk-agent/1.8.1](https://registry.npmjs.org/sshpk-agent/1.8.1)
  - sshpk: ">=1.14.1 < 1.17.0"
- [tabula/1.10.0](https://registry.npmjs.org/tabula/1.10.0)
  - dashdash: "1.x >=1.8"
- [then-fs/2.0.0](https://registry.npmjs.org/then-fs/2.0.0)
  - promise: ">=3.2 <8"
- [thenify-all/1.6.0](https://registry.npmjs.org/thenify-all/1.6.0)
  - thenify: ">= 3.1.0 < 4"
- [through2/0.6.5](https://registry.npmjs.org/through2/0.6.5)
  - readable-stream: ">=1.0.33-1 <1.1.0-0"
  - xtend: ">=4.0.0 <4.1.0-0"
- [websocket-driver/0.7.3](https://registry.npmjs.org/websocket-driver/0.7.3)
  - http-parser-js: ">=0.4.0 <0.4.11"

**Hyphen Ranges:**
- [apollo/2.21.0](https://registry.npmjs.org/apollo/2.21.0)
  - graphql: "14.0.2 - 14.2.0 || ^14.3.1"

**X-Ranges:**
- [cssauron2: 2.0.3](https://registry.npmjs.org/cssauron2/2.0.3)
  - through: "X.X.X"

**Doesn't look valid, but it's in the NPM registry**:
- [blessed-contrib: 4.8.18](https://registry.npmjs.org/blessed-contrib/4.8.18)
  - lodash: "~>=4.17.11"

It looks like the work for unions was started in [`comparator.rs`](https://github.com/steveklabnik/semver-parser/blob/master/src/comparator.rs), but right now it's treated separately from `VersionReq` and isn't used from `semver`. It also seems to be named incorrectly. A `node-semver` comparator is equivalent to a predicate, not a union of predicates.

**Comment by kira-bruneau** [comment] 2019-11-21 01:05
After looking into this further, space delimited intersections have been supported since cffb6eb, but `semver` still uses an older version of `semver-parser`.

I've started work on supporting predicate unions in VersionReq, but it will introduce some backwards incompatible changes.
